package myTest;

// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class LocalisationTest extends BaseTest {
 public WebDriver driver;
   public Map<String, Object> vars;
    JavascriptExecutor js;


    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        driver.get("https://www.quandoo.de/en/result?destination=berlin");
        driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    public LocalisationTest(WebDriver driver, WebDriver driver1) {
        super(driver);
        this.driver = driver1;
    }

    @Test
    public void clickOnTheChangeLanguageButton() {


        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".sc-1vpjxqi-0 > b"));
            assert (elements.size() > 0);
        }
       // driver.findElement(By.cssSelector(".sc-1vpjxqi-0 > b")).click();
        {
            List<WebElement> elements = driver.findElements(By.linkText("Deutsch"));
            assert (elements.size() > 0);
        }
      //  driver.findElement(By.linkText("Italiano")).click();
        {
            List<WebElement> elements = driver.findElements(By.id("content-wrapper"));
            assert (elements.size() > 0);
        }

    }
}
