package Quandoo;// Generated by Selenium IDE

import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.*;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.List;

public class FunctionalTests {

    private WebDriver driver;

    @Before
    public void setUp() {
        
        driver = new ChromeDriver();
        driver.get("https://www.quandoo.de/en");
        driver.manage().window().setSize(new Dimension(1829, 1038));
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void singUp() {
        driver.get("https://www.quandoo.de/en/result?destination=berlin");
        driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
        driver.manage().window().setSize(new Dimension(1440, 876));
        {
            List<WebElement> elements = driver.findElements(By.linkText("Sign up"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.linkText("Sign up")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".iTacbz"));
            assert (elements.size() > 0);
        }
    }


    @Test
    public void checkRelevance() {
        driver.get("https://www.quandoo.de/en/result?destination=berlin");
        driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
        driver.manage().window().setSize(new Dimension(1440, 876));
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".sc-17n3422-1"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.cssSelector(".sc-17n3422-1")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".NpmQM"));
            assert (elements.size() > 0);
        }
    }

    @Test
    public void checkShowAllCuisine() {
        driver.get("https://www.quandoo.de/en/result?destination=berlin");
        driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
        driver.manage().window().setSize(new Dimension(1440, 876));
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".ulye33-7"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.cssSelector(".ulye33-7")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".ulye33-1:nth-child(2)"));
            assert (elements.size() > 0);
        }
    }

    {
        driver.get("https://www.quandoo.de/en/result?destination=berlin");
        driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
        driver.manage().window().setSize(new Dimension(1440, 876));
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".sc-1vpjxqi-0 > b"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.cssSelector(".sc-1vpjxqi-0 > b")).click();
        {
            List<WebElement> elements = driver.findElements(By.linkText("Deutsch"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.linkText("Italiano")).click();
        {
            List<WebElement> elements = driver.findElements(By.id("content-wrapper"));
            assert (elements.size() > 0);
        }
    }

    @Test
    public void checkShowLessCuisine() {
        driver.get("https://www.quandoo.de/en/result?destination=berlin");
        driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
        driver.manage().window().setSize(new Dimension(1440, 876));
        JavascriptExecutor js = null;
        js.executeScript("window.scrollTo(0,115)");
        driver.findElement(By.cssSelector(".ulye33-7")).click();
        js.executeScript("window.scrollTo(0,299)");
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".ulye33-7"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.cssSelector(".ulye33-7")).click();
        driver.findElement(By.cssSelector(".ulye33-1:nth-child(1) .apti0f-5")).click();
        driver.findElement(By.cssSelector(".ulye33-1:nth-child(2) > .ulye33-2")).click();
        driver.findElement(By.cssSelector(".ulye33-1:nth-child(3) .apti0f-5")).click();
        js.executeScript("window.scrollTo(0,137)");
        driver.findElement(By.cssSelector(".ulye33-1:nth-child(4) .apti0f-5")).click();
        driver.findElement(By.cssSelector(".ulye33-1:nth-child(5) .apti0f-5")).click();
        driver.findElement(By.cssSelector(".ulye33-1:nth-child(6) .apti0f-5")).click();
    }

    @Test
    public void login() {
        driver.get("https://www.quandoo.de/en/result?destination=berlin");
        driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
        driver.manage().window().setSize(new Dimension(1440, 876));
        {
            List<WebElement> elements = driver.findElements(By.linkText("Log in"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.linkText("Log in")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".iTacbz"));
            assert (elements.size() > 0);
        }
    }

    @Test
    public void checkSingUp() {
        driver.get("https://www.quandoo.de/en/result?destination=berlin");
        driver.findElement(By.id("CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll")).click();
        driver.manage().window().setSize(new Dimension(1440, 876));
        {
            List<WebElement> elements = driver.findElements(By.linkText("Sign up"));
            assert (elements.size() > 0);
        }
        driver.findElement(By.linkText("Sign up")).click();
        {
            List<WebElement> elements = driver.findElements(By.cssSelector(".iTacbz"));
            assert (elements.size() > 0);
        }
    }


}

}
